# -*- mode: ruby -*-
# # vi: set ft=ruby :

CONFIG = File.join(File.dirname(__FILE__), "platforms", "default.rb")
require CONFIG

if ENV.key?("PLATFORM")
  CONFIG_PLATFORM = File.join(File.dirname(__FILE__), "platforms", ENV["PLATFORM"] + ".rb")
  require CONFIG_PLATFORM
end

cluster = {
  "master" => { :roles => [ "master" ], :nodes => 3, :ip_offset => 100 },
  "slave" => { :roles => [ "slave" ], :nodes => 2, :ip_offset => 200 }
}

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
  config.vm.synced_folder '..', '/vagrant', type: 'rsync', rsync__auto: false, rsync__exclude: [ "packages", ".git" ]

  cluster.each do |n, c|
    (1..c[:nodes]).each do |i|
      name = "%s-%02d" %[ n, i ]
      ip = "#{$network}.#{i+c[:ip_offset]}"

      script = "printf 'EXHIBITOR_HOSTNAME=#{ip}\n' >> /etc/environment &&\n" \
        + render_installer(n, c) \
        + "printf 'MARATHON_HOSTNAME=#{ip}\nMESOS_HOSTNAME=#{ip}\nMESOS_IP=#{ip}\n'>> /opt/mesosphere/etc/cloudenv"

      puts "Provisioner script: #{script}"
      config.vm.define name do |instance|
        instance.vm.provision "shell", inline: script
        instance.vm.box = $box
        instance.vm.hostname = name
        instance.vm.network :private_network, ip: ip, :dev => "virbr0"
      end
    end
  end
end
