---
# GLOBAL PARAMETERS
# An arbitary name for your DCOS cluster
cluster_name:
# The URL where the installer can download the configuration built with DCOS_generate utility.
bootstrap_url:
# Garbage collection delay. Shouldn't be touched unless you're a pro.
gc_delay:

# MASTER DISCOVERY
# Master discovery options: static, vrrp, or zookeeper. Sub options for a given discovery method are required for that method. 
master_discovery:
  # For cloud environment only: Use an external proxy for the masters that lives at a static IP, for example, haproxy or nginx. 
  cloud_dynamic: false
  # Use the Mesos agents to discover the masters by giving each agent a static list of master IPs. The masters must not change IP addresses, and if a master is replaced, the new master must take the old master’s IP address.
  static: true # true/false
    # Specify a JSON-formatted list of your static master IP addresses.
    master_list: YOUR_IP_LIST_HERE_PLEASE
  # Use keepalived with a VIP. You are required to maintain this VIP infrastructure
  vrrp: false # true/false
    # Specify the virtual router ID of the keepalived cluster. You must use the same virtual router ID across your cluster.
    keepalived_router_id: 
    # Specify the interface that keepalived uses.
    keepalived_interface:
    # If you’ve set your auth to PASS, specify the same password that you set in your configuration file. 
    keepalived_pass:
    # Specify the VIP in use by your keepalived cluster.
    keepalived_virtual_ipaddress:

# EXHIBITOR STORAGE BACKEND
# This parameter specifies the name of Exhibitor storage backend. During DCOS installation, a storage system is required for configuring and orchestrating Zookeeper with Exhibitor on the master nodes. Exhibitor automatically configures your Zookeeper installation on the master nodes during your DCOS installation. The available options are zookeeper, aws_s3, and shared_filesystem.
exhibitor_storage_backend:
  zookeeper: true # true/false
    # This parameter specifies a comma-separated list of one or more Zookeeper node IP addresses to use for configuring the internal Exhibitor instances. Exhibitor uses this Zookeeper cluster to orchestrate it’s configuration.
    exhibitor_zk_hosts: PRECONFIGURED_ZK_IPS
    # This parameter specifies the filepath that Exhibitor uses to store data, including the zoo.cfg file.
    exhibitor_zk_path: /SOME/PATH
  # Use S3 as the exhibitor backend
  aws_s3: false # true/false
    # This parameter specifies AWS key ID.
    aws_access_key_id:    
    # This parameter specifies AWS region for your S3 bucket.
    aws_region:
    # This parameter specifies AWS secret access key.
    aws_secret_access_key:
    # This parameter specifies name of your S3 bucket.
    s3_bucket:
    # This parameter specifies S3 prefix to be used within your S3 bucket to be used by Exhibitor.
    s3_prefix:
    
