#!/bin/bash
set -euo pipefail

# Checkout pkgpanda at the same commit as packages/pkgpanda/buildinfo.json uses to ensure that any
# given dcos-image commit build always uses the same pkgpanda

# If it already exists, fetch, otherwise clone
if [ ! -d ext/pkgpanda ]; then
  git clone git@github.com:mesosphere/pkgpanda.git ext/pkgpanda
else
  git -C ext/pkgpanda fetch origin -t +refs/heads/*:refs/remotes/origin/*
fi

hash jq 2>/dev/null || { echo >&2 "jq must be in path. Get it from https://stedolan.github.io/jq/. Aborting"; exit 1; }

pkgpanda_commit=$(jq -r '.single_source.ref' packages/pkgpanda/buildinfo.json)

pushd ext/pkgpanda
git checkout -qf $pkgpanda_commit
popd
