#!/bin/bash
set -euo pipefail

# If it already exists, fetch, otherwise clone
if [ ! -d ext/dcos-installer ]; then
  git clone git@github.com:mesosphere/dcos-installer.git ext/dcos-installer
else
  git -C ext/dcos-installer fetch origin -t +refs/heads/*:refs/remotes/origin/*
fi

dcos_installer_commit=21d233e98398e73e3374a39d1238487a4a08c8f4
pushd ext/dcos-installer
git checkout -qf $dcos_installer_commit
popd

# Compile the installer UI components
# Read basic argument for whether or not we should build the ui
SKIP_UI=false
if [ $# -gt 0 ]; then
  if [ "$1" == "--skip-ui-build" ]; then
    SKIP_UI=true
  fi
fi

if ! $SKIP_UI; then
  docker run --rm=true -v $(pwd)/ext/dcos-installer:/code -w /code/ui node:4.2.6 npm install
  docker run --rm=true -v $(pwd)/ext/dcos-installer:/code -w /code/ui node:4.2.6 ./node_modules/.bin/gulp dist
fi
