#!/bin/bash
set -o errexit -o nounset -o pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <regex>"
    exit 1
fi


grep -r "$1" gen/
grep "$1" packages/*/build
grep "$1" packages/*/buildinfo.json
grep "$1" *.py *.sh
grep -r "$1" test/ fleet/
