#!/bin/bash
set -o nounset -o pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <regex>"
    exit 1
fi


grep -r "$1" gen/ docker/ diag/ docs/ scripts/ test/ fleet/ providers/ packages/*/extra
grep "$1" packages/*/build
grep "$1" packages/*/buildinfo.json
grep "$1" *.py
