#!/bin/bash
#
# Simple helper script to get a localhost dcos-image development environment up
# and running with clone of pkgpanda.
#
# Expects that it is being run inside of a virtual environment.
#
# A checkout of pkgpanda lives at `ext/pkgpanda`. To work on pkgpanda edit
# that checkout.

set -o errexit -o nounset -o pipefail

: ${VIRTUAL_ENV?"Must be run in a python virtual environment"}

./fetch_pkgpanda
./fetch_installer

# Install the packages in editable mode to the virtual environment.
pip install -e ext/pkgpanda
pip install -e ext/dcos-installer
pip install -e $PWD
