#!/bin/bash
set -o errexit -o nounset -o pipefail

./fetch_pkgpanda

# NOTE: If the directory already exists that is indeed a hard error. Should be
# cleaned up between builds to guarantee we get the artifacts we expect.
mkdir wheelhouse || (echo wheelhouse folder must be deleted before prep_teamcity is rerun && exit 1)

if [ -d ext/dcos-image ]
then
  rm -rf ext/dcos-image
fi

# Make a clean copy of pkgpanda so the python artifacts build fast
git clone file://$PWD ext/dcos-image
git -C ext/dcos-image checkout -qf `git rev-parse --verify HEAD^{commit}`

# Download distro independent artifacts
pip install --download wheelhouse ext/dcos-image
pip install --download wheelhouse ext/pkgpanda

# Make the wheels, they will be output into the folder `wheelhouse` by default.
pip wheel --no-index --find-links=wheelhouse ext/pkgpanda
pip wheel --no-index --find-links=wheelhouse ext/dcos-image

# Install the wheels
pip install --no-index --find-links=wheelhouse dcos-image pkgpanda
