#!/usr/bin/env python3
# ENV['channelname'] && ['bootstrap_id'] need to be set here.
import os

from dcos_installer import DcosInstaller

def main():
    os.environ["CHANNEL_NAME"] = "testing/continuous"
    os.environ["BOOTSTRAP_ID"] = '0026f44d8574d508104f1e7e7a163e078e69990b'

    DcosInstaller()

if __name__ == '__main__':
    main()
