# Mesos Cluster Configuration
#
# Created M. Massenzio, 2015-04-27

imports: 
- path: vm_master.jinja
- path: vm_slave.jinja
- path: network.jinja
- path: cloud-config.yaml

resources:
- name: master-cluster
  type: vm_master.jinja
  properties:
    base_name: test
    masters: 1
    master_quorum: 1
    disk_size: 10G
    zone: us-central1-a
    machine: n1-standard-1
    bootstrap_url: http://s3.amazonaws.com/downloads.mesosphere.io/dcos/EarlyAccess
    ssh_key: test_ssh_key
    network: test-network

- name: slaves-cluster
  type: vm_slave.jinja
  properties:
    base_name: test
    nodes: 1
    machine: n1-standard-1
    disk_size: 15G
    zone: us-central1-a
    ssh_key: test_ssh_key
    bootstrap_url: http://s3.amazonaws.com/downloads.mesosphere.io/dcos/EarlyAccess
    network: test-network

- name: subnet
  type: network.jinja
  properties:
    base_name: mesos-internal
    zone: us-central1-a
    network_pool: 10.10.0.0/16
    admin_range: 10.10.0.0/16
    network: test-network
