write_files:
  - path: /etc_master/dns_config_master
    content: |
      TRY_LOCALHOST=true
  - path: /etc/dns_config
    content: |
      MASTER_SOURCE=master_list
      RESOLVERS={{range  $r := .DnsResolvers}}{{$r}} {{end}}
  - path: /etc/master_list
    content: |
      {{ .MasterList }}
