package:
  - path: /etc/exhibitor
    content: |
      EXHIBITOR_BACKEND=AWS_S3
      AWS_REGION={{ aws_region }}
      AWS_S3_BUCKET={{ s3_bucket }}
      AWS_S3_PREFIX={{ s3_prefix }}
  - path: /etc/exhibitor.properties
    content: |
      com.netflix.exhibitor.s3.access-key-id={{ aws_access_key_id }}
      com.netflix.exhibitor.s3.access-secret-key={{ aws_secret_access_key }}
