  - path: /etc/exhibitor
    content: |
      AWS_REGION={{ aws_region }}
      AWS_ACCESS_KEY_ID={{ aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}
      AWS_S3_BUCKET={{ s3_bucket }}
      AWS_S3_PREFIX={{ s3_prefix }}
      EXHIBITOR_WEB_UI_PORT=8181
