write_files:
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/pkginfo.json
    content: |
      {
        "environment": {
          "PROVIDER": "vagrant"
        }
      }
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/etc/cloudenv
    content: |
      ZOOKEEPER_CLUSTER_SIZE=1
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/etc/mesos-master-provider
    content: |
      MESOS_CLUSTER={{ cluster_name }}
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/etc/exhibitor
    content: |
      EXHIBITOR_BACKEND=SHARED_FS
      ZOOKEEPER_CLUSTER_SIZE=1
      EXHIBITOR_FSCONFIGDIR=/var/run/exhibitor
