write_files:
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/pkginfo.json
    content: |
      {
        "environment": {
          "PROVIDER": "vagrant"
        }
      }
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/etc/cloudenv
    content: |
      MASTER_ELB=127.0.0.1
      ZOOKEEPER_CLUSTER_SIZE=1
      FALLBACK_DNS={{ fallback_dns }}
      MARATHON_HOSTNAME=$private_ipv4
      MESOS_HOSTNAME=$private_ipv4
      MESOS_IP=$private_ipv4
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/etc/mesos-master-provider
    content: |
      MESOS_CLUSTER={{ cluster_name }}
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/etc/exhibitor
    content: |
      EXHIBITOR_FSCONFIGDIR=/var/run/exhibitor
      EXHIBITOR_WEB_UI_PORT=8181
      EXHIBITOR_HOSTNAME=$private_ipv4
  - path: /etc/mesosphere/setup-packages/dcos-provider-vagrant--setup/etc/exhibitor
    content: |
      EXHIBITOR_FSCONFIGDIR=/var/run/exhibitor
      EXHIBITOR_WEB_UI_PORT=8181
      EXHIBITOR_HOSTNAME=$private_ipv4
  - path: /etc/resolv.conf
    content: 'nameserver 8.8.8.8'
coreos:
  units:
    - name: config-writer.service
      command: start
      content: |
        [Unit]
        Description=Write out dynamic config values
        [Service]
        Type=oneshot
        EnvironmentFile=/etc/environment
        # Marathon depends on `hostname` resolution working
        ExecStart=/usr/bin/bash -c "echo ${COREOS_PRIVATE_IPV4} $(hostname) > /etc/hosts"
