#!/opt/mesosphere/bin/python

import os
import sys


NAMESERVERS = ['198.51.100.1', '198.51.100.2', '198.51.100.3']


if len(sys.argv) != 2:
    print('Usage: gen_resolvconf.py RESOLV_CONF_PATH', file=sys.stderr)
    print('Received: {}'.format(sys.argv), file=sys.stderr)
    sys.exit(-1)
resolvconf_path = sys.argv[1]

contents = """# Generated by gen_resolvconf.py. Do not edit.
# Change configuration options by changing DCOS cluster configuration.
# This file must be overwritten regularly for proper cluster operation around
# master failure.

options timeout:1
options attempts:3

"""

if 'SEARCH' in os.environ:
    contents += "search {}\n".format(os.environ['SEARCH'])


for ns in NAMESERVERS:
    contents += "nameserver {}\n".format(ns)

# Generate the resolv.conf config
print('Updating {}'.format(resolvconf_path))
with open(resolvconf_path, 'w') as f:
    print(contents, file=sys.stderr)
    f.write(contents)

sys.exit(0)
