
# Mesos Cluster Configuration
#
# Created M. Massenzio, 2015-04-27

imports:
- path: vm_master.jinja
- path: vm_slave.jinja
- path: network.jinja
- path: cloud-config.jinja

resources:
- name: master-cluster
  type: vm_master.jinja
  properties:
    base_name: mesos
    masters: 3
    disk_size: 10G
    zone: us-central1-a
    machine_type: n1-standard-1
    bootstrap_url: http://storage.googleapis.com/bootstrap-dcos
    network: mesos-network

- name: slaves-cluster
  type: vm_slave.jinja
  properties:
    base_name: mesos
    nodes: 3
    machine_type: n1-standard-1
    disk_size: 15G
    zone: us-central1-a
    bootstrap_url: http://storage.googleapis.com/bootstrap-dcos
    network: mesos-network

- name: subnet
  type: network.jinja
  properties:
    zone: us-central1-a
    network_pool: 10.10.0.0/16
    admin_range: 0.0.0.0/0
    network: mesos-network
