package:
  - path: /etc/cloudenv
    content: |
      AWS_REGION={ "Ref" : "AWS::Region" }
      AWS_STACK_ID={ "Ref" : "AWS::StackId" }
      AWS_STACK_NAME={ "Ref" : "AWS::StackName" }
      AWS_IAM_MASTER_ROLE_NAME={ "Ref" : "MasterRole" }
      AWS_IAM_SLAVE_ROLE_NAME={ "Ref" : "SlaveRole" }
      AWS_ACCESS_KEY_ID={ "Ref" : "HostKeys" }
      AWS_SECRET_ACCESS_KEY={ "Fn::GetAtt" : [ "HostKeys", "SecretAccessKey" ] }
      ZOOKEEPER_CLUSTER_SIZE={{ num_masters }}
  - path: /etc/mesos-master-provider
    content: |
      MESOS_CLUSTER={ "Ref" : "AWS::StackName" }
  - path: /etc/exhibitor
    content: |
      EXHIBITOR_BACKEND=AWS_S3
      AWS_REGION={ "Ref" : "AWS::Region" }
      AWS_S3_BUCKET={ "Ref" : "ExhibitorS3Bucket" }
      AWS_S3_PREFIX={ "Ref" : "AWS::StackName" }
  - path: /etc/exhibitor.properties
    content: |
      com.netflix.exhibitor.s3.access-key-id={ "Ref" : "HostKeys" }
      com.netflix.exhibitor.s3.access-secret-key={ "Fn::GetAtt" : [ "HostKeys", "SecretAccessKey" ] }
  - path: /etc/dns_config
    content: |
      MASTER_SOURCE=exhibitor
      EXHIBITOR_ADDRESS={ "Fn::GetAtt" : [ "InternalMasterLoadBalancer", "DNSName" ] }
      RESOLVERS={{ resolvers_str }}
