package:
  - path: /etc/cfn_signal_metadata
    content: |
      AWS_REGION={ "Ref" : "AWS::Region" }
      AWS_STACK_ID={ "Ref" : "AWS::StackId" }
      AWS_STACK_NAME={ "Ref" : "AWS::StackName" }
      AWS_IAM_MASTER_ROLE_NAME={ "Ref" : "MasterRole" }
      AWS_IAM_SLAVE_ROLE_NAME={ "Ref" : "SlaveRole" }
