write_files:
  - path: /etc/keepalived
    content: |
      KEEPALIVED_VIRTUAL_IPADDRESS={{ keepalived_virtual_ipaddress }}
      KEEPALIVED_INTERFACE={{ keepalived_interface }}
      KEEPALIVED_ROUTER_ID={{ keepalived_router_id }}
      KEEPALIVED_PASS={{ keepalived_pass }}
