write_files:
  - path: /etc/keepalived
    content: |
      KEEPALIVED_VIRTUAL_IPADDRESS={{ keepalived_virtual_ipaddress }}
      KEEPALIVED_INTERFACE={{ keepalived_interface }}
      KEEPALIVED_ROUTER_ID={{ keepalived_router_id }}
      KEEPALIVED_PASS={{ keepalived_pass }}
  - path: /etc/cloudenv
    content: |
      MASTER_ELB={{ keepalived_virtual_ipaddress }}
      ZOOKEEPER_CLUSTER_SIZE={{ num_masters }}
      # Must set FALLBACK_DNS to an AWS region-specific DNS server which returns
      # the internal IP when doing lookups on AWS public hostnames.
      FALLBACK_DNS={{ fallback_dns }}
