root:
  - path: /etc/mesosphere/cluster-id
    permissions: "0644"
    content: |
      { "Ref" : "AWS::StackId" }
package:
  - path: /pkginfo.json
    content: |
      {
        "environment": {
          "PROVIDER": "onprem"
        }
      }
  - path: /etc/mesos-master-provider
    content: |
      MESOS_CLUSTER={{ cluster_name }}
