write_files:
  - path: /pkginfo.json
    content: |
      {
        "environment": {
          "PROVIDER": "onprem"
        }
      }
  - path: /etc/cloudenv
    content: |
      ZOOKEEPER_CLUSTER_SIZE={{ num_masters }}
      MASTER_ELB={{ master_lb }}
      EXTERNAL_ELB={{ external_master_lb }}
      # Must set FALLBACK_DNS to an AWS region-specific DNS server which returns
      # the internal IP when doing lookups on AWS public hostnames.
      FALLBACK_DNS={{ fallback_dns }}
  - path: /etc/mesos-master-provider
    content: |
      MESOS_CLUSTER={{ cluster_name }}
  - path: /etc/exhibitor
    content: |
      AWS_REGION={{ aws_region }}
      AWS_ACCESS_KEY_ID={{ aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}
      AWS_S3_BUCKET={{ s3_bucket }}
      AWS_S3_PREFIX={{ s3_prefix }}
      EXHIBITOR_WEB_UI_PORT=8181
