write_files:
  - path: /pkginfo.json
    content: |
      {
        "environment": {
          "PROVIDER": "onprem"
        }
      }
  - path: /etc/cloudenv
    content: |
      ZOOKEEPER_CLUSTER_SIZE={{ num_masters }}
  - path: /etc/mesos-master-provider
    content: |
      MESOS_CLUSTER={{ cluster_name }}
