write_files:
  - path: /pkginfo.json
    content: |
      {
        "environment": {
          "PROVIDER": "onprem"
        }
      }
  - path: /etc/mesos-master-provider
    content: |
      MESOS_CLUSTER={{ cluster_name }}
