root:
  - path: /etc/systemd/system/dcos-link-env.service
    permissions: "0644"
    content: |
      [Unit]
      Before=dcos.target
      [Service]
      Type=oneshot
      StandardOutput=journal+console
      StandardError=journal+console
      ExecStartPre=/usr/bin/mkdir -p /etc/profile.d
      ExecStart=/usr/bin/ln -sf /opt/mesosphere/environment.export /etc/profile.d/dcos.sh
  - path: /etc/systemd/system/dcos-download.service
    permissions: "0644"
    content: |
      [Unit]
      Description=Pkgpanda: Download the DCOS
      After=network-online.target
      Wants=network-online.target
      ConditionPathExists=!/opt/mesosphere/
      [Service]
      EnvironmentFile=/etc/mesosphere/setup-flags/bootstrap-id
      Type=oneshot
      StandardOutput=journal+console
      StandardError=journal+console
      ExecStartPre=/usr/bin/curl --fail --retry 20 --continue-at - --location --silent --show-error --verbose --output /tmp/bootstrap.tar.xz {{ bootstrap_url }}/bootstrap/${BOOTSTRAP_ID}.bootstrap.tar.xz
      ExecStartPre=/usr/bin/mkdir -p /opt/mesosphere
      ExecStart=/usr/bin/tar -axf /tmp/bootstrap.tar.xz -C /opt/mesosphere
      ExecStartPost=-/usr/bin/rm -f /tmp/bootstrap.tar.xz
  - path: /etc/systemd/system/dcos-setup.service
    permissions: "0644"
    content: |
      [Unit]
      Description=Pkgpanda: Specialize DCOS for this host.
      Requires=dcos-download.service
      After=dcos-download.service
      [Service]
      Type=oneshot
      StandardOutput=journal+console
      StandardError=journal+console
      EnvironmentFile=/opt/mesosphere/environment
      ExecStart=/opt/mesosphere/bin/pkgpanda setup --no-block-systemd
      [Install]
      WantedBy=multi-user.target
  - path: /usr/sbin/policy-rc.d
    permissions: "0755"
    content: |
      #!/usr/bin/bash
      if [[ "$1" == "docker" && "$2" == "start" ]]; then exit 101; fi
  - path: /etc/systemd/system/docker.service.d/execstart.conf
    permissions: "0644"
    content: |
      [Service]
      ExecStartPre=/bin/sh -ec "until df|grep /mnt;do echo waiting for /mnt;sleep 10;done"
      # Disable unit default ExecStart statements with an empty assignment
      ExecStart=
      ExecStart=/usr/bin/docker daemon -H fd:// --graph=/mnt/docker --storage-driver=overlay
  - path: /etc/systemd/system/docker.socket
    permissions: "0644"
    content: |
      [Unit]
      PartOf=docker.service
      [Socket]
      ListenStream=/var/run/docker.sock
      SocketMode=0660
      SocketUser=root
      SocketGroup=docker
      ListenStream=2375
      BindIPv6Only=both
      [Install]
      WantedBy=sockets.target
  - path: /etc/systemd/system/dcos-config-writer.service
    permissions: "0644"
    content: |
      [Unit]
      Description=Pkgpanda: Write out dynamic config values
      Requires=dcos-setup.service
      After=dcos-setup.service
      [Service]
      Type=oneshot
      EnvironmentFile=/etc/environment
      EnvironmentFile=/opt/mesosphere/environment
      # config-writer service should eventually be removed, see: DCOS-3719
      ExecStart=/usr/bin/bash -c "echo $(detect_ip) $(hostname) > /etc/hosts"
runcmd:
    - [ ln, -s, /bin/rm, /usr/bin/rm ]
    - [ ln, -s, /bin/mkdir, /usr/bin/mkdir ]
    - [ ln, -s, /bin/tar, /usr/bin/tar ]
    - [ ln, -s, /bin/ln, /usr/bin/ln ]
    - [ ln, -s, /bin/cp, /usr/bin/cp ]
    - [ ln, -s, /bin/systemctl, /usr/bin/systemctl ]
    - [ ln, -s, /bin/mount, /usr/bin/mount ]
    - [ ln, -s, /bin/bash, /usr/bin/bash ]
    - [ systemctl, stop, resolvconf.service ]
    - [ systemctl, disable, resolvconf.service ]
    - [ systemctl, stop, lxc-net.service ]
    - [ systemctl, disable, lxc-net.service ]
    - [ systemctl, mask, lxc-net.service ]
    - [ cp, -p, /etc/resolv.conf, /tmp/resolv.conf ]
    - [ rm, -f, /etc/resolv.conf ]
    - [ cp, -p, /tmp/resolv.conf, /etc/resolv.conf ]
    - [ systemctl, start, dcos-link-env.service ]
    - [ systemctl, start, dcos-download.service ]
    - [ systemctl, start, dcos-setup.service ]
    - [ systemctl, start, dcos-config-writer.service ]
    - [ apt-get, -y, update ]
    - curl -fLsSv --retry 20 -C - -o /tmp/docker-engine_1.9.1-0~wily_amd64.deb http://az837203.vo.msecnd.net/dcos-deps/docker-engine_1.9.1-0~wily_amd64.deb
    - DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/docker-engine_1.9.1-0~wily_amd64.deb
    - [ systemctl, restart, docker ]
