write_files:
  - path: /etc/mesosphere/setup-packages/dcos-provider-azure--setup/pkginfo.json
    content: |
      {
        "environment": {
          "PROVIDER": "azure"
        }
      }
  - path: /etc/mesosphere/setup-packages/dcos-provider-azure--setup/etc/cloudenv
    content: |
      # TODO(cmaloney): Add cluster general info for analytics here
      ZOOKEEPER_CLUSTER_SIZE={{ num_masters }}
  - path: /etc/mesosphere/setup-packages/dcos-provider-azure--setup/etc/mesos-master-provider
    content: |
      MESOS_CLUSTER=[[[variables('uniqueName')]]]
  - path: /etc/mesosphere/setup-packages/dcos-provider-azure--setup/etc/exhibitor
    content: |
      EXHIBITOR_BACKEND=AZURE
      AZURE_CONTAINER=dcos-exhibitor
      AZURE_PREFIX=[[[variables('uniqueName')]]]
  - path: /etc/mesosphere/setup-packages/dcos-provider-azure--setup/etc/exhibitor.properties
    content: |
      com.netflix.exhibitor.azure.account-name=[[[variables('storageAccountName')]]]
      com.netflix.exhibitor.azure.account-key=[[[listKeys(resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName')), '2015-05-01-preview').key1]]]
  - path: /etc/mesosphere/setup-packages/dcos-provider-azure--setup/etc/dns_config
    content: |
      MASTER_SOURCE=exhibitor
      # TODO(cmaloney): Switch to VRRP or an internal master load balancer
      EXHIBITOR_ADDRESS=[[[reference('masterNodeNic0').ipConfigurations[0].properties.privateIPAddress]]]
      RESOLVERS={{ resolvers_str }}
  - path: etc/mesosphere/cluster-id
    permissions: "0644"
    content: |
      [[[resourceid('Microsoft.Resources/deployments', deployment().name)]]]
coreos:
  units:
    - name: var-lib.mount
      command: start
      content: |
        [Unit]
        Description=Mount /var/lib
        Before=dbus.service
        [Mount]
        What=/dev/sdb1
        Where=/var/lib
        Type=ext4
    - name: config-writer.service
      command: start
      content: |
        [Unit]
        Description=Write out dynamic config values
        [Service]
        Type=oneshot
        EnvironmentFile=/etc/environment
        # Various DCOS universe packages depend on local hostname resolution
        # working (e.g. `ping $(hostname)` must work). The config-writer
        # service can be removed when we are certain that all DCOS packages
        # work properly in environments where hostname DNS resolution is not
        # functional. See: DCOS-3719
        ExecStart=/usr/bin/bash -c "echo $private_ipv4 $(hostname) > /etc/hosts"
