write_files:
  - path: /etc/mesosphere/setup-packages/dcos-provider-aws--setup/pkginfo.json
    content: |
      {
        "environment": {
          "PROVIDER": "aws"
        }
      }
  - path: /etc/mesosphere/setup-packages/dcos-provider-aws--setup/etc/cloudenv
    content: |
      AWS_REGION={ "Ref" : "AWS::Region" }
      AWS_STACK_ID={ "Ref" : "AWS::StackId" }
      AWS_STACK_NAME={ "Ref" : "AWS::StackName" }
      AWS_ACCESS_KEY_ID={ "Ref" : "HostKeys" }
      AWS_SECRET_ACCESS_KEY={ "Fn::GetAtt" : [ "HostKeys", "SecretAccessKey" ] }
      ZOOKEEPER_CLUSTER_SIZE={master_count}
      MASTER_ELB={ "Fn::GetAtt" : [ "InternalMasterLoadBalancer", "DNSName" ] }
      EXTERNAL_ELB={ "Fn::GetAtt" : [ "ElasticLoadBalancer", "DNSName" ] }
      # Must set FALLBACK_DNS to an AWS region-specific DNS server which returns
      # the internal IP when doing lookups on AWS public hostnames.
      FALLBACK_DNS={{ fallback_dns }}
  - path: /etc/mesosphere/setup-packages/dcos-provider-aws--setup/etc/mesos-master-provider
    content: |
      MESOS_CLUSTER={ "Ref" : "AWS::StackName" }
  - path: /etc/mesosphere/setup-packages/dcos-config--setup/etc/exhibitor
    content: |
      AWS_S3_BUCKET={ "Ref" : "ExhibitorS3Bucket" }
      AWS_S3_PREFIX={ "Ref" : "AWS::StackName" }
      EXHIBITOR_WEB_UI_PORT=8181

