write_files:
  - path: /etc/mesosphere/setup-flags/repository-url
    permissions: 0644
    owner: root
    content: |
      {{ bootstrap_url }}
  - path: /etc/mesosphere/setup-flags/bootstrap-id
    permissions: 0644
    owner: root
    content: |
      BOOTSTRAP_ID={{ bootstrap_id }}
