#!/bin/bash

function main {
  update_discovery_url
  apply
}

function apply {
  terraform apply
}

function update_discovery_url {
  cat <<EOF > "discovery_url.tf.json"
{
    "variable": {
        "discovery_url": {
            "description": "CoreOS unique discovery URL generated by create.sh",
            "default": "$(get_discovery_url)"
        }
    }
}
EOF
}

function get_discovery_url {
  out $(curl -sS https://discovery.etcd.io/new)
}

function msg { out "$*" >&2 ;}
function err { local x=$? ; msg "$*" ; return $(( $x == 0 ? 1 : $x )) ;}
function out { printf '%s\n' "$*" ;}

if [[ ${1:-} ]] && declare -F | cut -d' ' -f3 | fgrep -qx -- "${1:-}"
then "$@"
else main "$@"
fi
